
import javax.swing.JCheckBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author negi
 */
public class apti extends javax.swing.JPanel {

    
    JCheckBox cb[];
    makeChanges m = new makeChanges("apti");

    public apti() {
        initComponents();

        cb = new JCheckBox[]{cb1, cb1, cb2, cb3, cb4, cb5, cb16, cb7, cb8, cb9, cb10, cb6, cb12, cb13, cb14, cb15, cb11,
            cb17, cb18, cb19, cb20, cb21, cb22, cb23, cb24, cb25, cb26, cb27, cb28, cb29, cb30, cb31, cb32};

        m.show(cb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb1 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb30 = new javax.swing.JCheckBox();
        cb22 = new javax.swing.JCheckBox();
        cb21 = new javax.swing.JCheckBox();
        cb14 = new javax.swing.JCheckBox();
        cb23 = new javax.swing.JCheckBox();
        cb18 = new javax.swing.JCheckBox();
        cb11 = new javax.swing.JCheckBox();
        cb17 = new javax.swing.JCheckBox();
        cb20 = new javax.swing.JCheckBox();
        cb19 = new javax.swing.JCheckBox();
        cb9 = new javax.swing.JCheckBox();
        cb12 = new javax.swing.JCheckBox();
        cb13 = new javax.swing.JCheckBox();
        cb31 = new javax.swing.JCheckBox();
        cb15 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        cb32 = new javax.swing.JCheckBox();
        cb10 = new javax.swing.JCheckBox();
        cb8 = new javax.swing.JCheckBox();
        cb7 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb16 = new javax.swing.JCheckBox();
        cb26 = new javax.swing.JCheckBox();
        cb24 = new javax.swing.JCheckBox();
        cb29 = new javax.swing.JCheckBox();
        cb25 = new javax.swing.JCheckBox();
        cb27 = new javax.swing.JCheckBox();
        cb28 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        cb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb1.setText("Averages");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb4.setText("Ratio and proportion");
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });

        cb3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb3.setText("age");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });

        cb5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb5.setText("Profit and loss");
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });

        cb30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb30.setText("Blood Relation");
        cb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb30ActionPerformed(evt);
            }
        });

        cb22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb22.setText("Circular Arragement");
        cb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb22ActionPerformed(evt);
            }
        });

        cb21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb21.setText("Directions And Distance");
        cb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb21ActionPerformed(evt);
            }
        });

        cb14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb14.setText("Equations");
        cb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb14ActionPerformed(evt);
            }
        });

        cb23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb23.setText("Linear Arragement");
        cb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb23ActionPerformed(evt);
            }
        });

        cb18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb18.setText("Alphabetic series");
        cb18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb18ActionPerformed(evt);
            }
        });

        cb11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb11.setText("Progression");
        cb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb11ActionPerformed(evt);
            }
        });

        cb17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb17.setText("Surds and Indice");
        cb17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb17ActionPerformed(evt);
            }
        });

        cb20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb20.setText("Number Series");
        cb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb20ActionPerformed(evt);
            }
        });

        cb19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb19.setText("Number Systems");
        cb19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb19ActionPerformed(evt);
            }
        });

        cb9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb9.setText("Mensuration");
        cb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb9ActionPerformed(evt);
            }
        });

        cb12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb12.setText("Verbal Ability");
        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });

        cb13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb13.setText("Data Sufficiency");
        cb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb13ActionPerformed(evt);
            }
        });

        cb31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb31.setText("Logarthims");
        cb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb31ActionPerformed(evt);
            }
        });

        cb15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb15.setText("Data- Interpretation");
        cb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb15ActionPerformed(evt);
            }
        });

        cb6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb6.setText("Time And Distance");
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });

        cb32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb32.setText("Permutation and Combination");
        cb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb32ActionPerformed(evt);
            }
        });

        cb10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb10.setText("HCF And LCM");
        cb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb10ActionPerformed(evt);
            }
        });

        cb8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb8.setText("Time and work");
        cb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb8ActionPerformed(evt);
            }
        });

        cb7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb7.setText("Partnership");
        cb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb7ActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb2.setText("Simple intrest");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        cb16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb16.setText("Alligation and mixture");
        cb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb16ActionPerformed(evt);
            }
        });

        cb26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb26.setText("Ranking (or)  Odering");
        cb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb26ActionPerformed(evt);
            }
        });

        cb24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb24.setText("Coded Inequalities");
        cb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb24ActionPerformed(evt);
            }
        });

        cb29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb29.setText("Element Series");
        cb29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb29ActionPerformed(evt);
            }
        });

        cb25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb25.setText("Alphabet Test");
        cb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb25ActionPerformed(evt);
            }
        });

        cb27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb27.setText("Coding And Decoding");
        cb27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb27ActionPerformed(evt);
            }
        });

        cb28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb28.setText("Percentage");
        cb28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb1)
                    .addComponent(cb26)
                    .addComponent(cb31)
                    .addComponent(cb21)
                    .addComponent(cb16)
                    .addComponent(cb11)
                    .addComponent(cb6))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb22)
                                    .addComponent(cb7)
                                    .addComponent(cb27))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb23)
                                            .addComponent(cb18)
                                            .addComponent(cb13)
                                            .addComponent(cb8)
                                            .addComponent(cb28))
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb29)
                                            .addComponent(cb14)
                                            .addComponent(cb9)
                                            .addComponent(cb4)
                                            .addComponent(cb19)
                                            .addComponent(cb24)))))
                            .addComponent(cb2)
                            .addComponent(cb17)
                            .addComponent(cb12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cb5)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb10)
                                    .addComponent(cb15)
                                    .addComponent(cb20)
                                    .addComponent(cb25)
                                    .addComponent(cb30))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb32)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb2)
                    .addComponent(cb3)
                    .addComponent(cb4)
                    .addComponent(cb5)
                    .addComponent(cb1))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb6)
                    .addComponent(cb8)
                    .addComponent(cb7)
                    .addComponent(cb9)
                    .addComponent(cb10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb11)
                            .addComponent(cb12)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb13)
                            .addComponent(cb14)
                            .addComponent(cb15))
                        .addGap(9, 9, 9)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb16)
                    .addComponent(cb17)
                    .addComponent(cb18)
                    .addComponent(cb19)
                    .addComponent(cb20))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb21)
                    .addComponent(cb22)
                    .addComponent(cb23)
                    .addComponent(cb24)
                    .addComponent(cb25))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb26)
                    .addComponent(cb27)
                    .addComponent(cb28)
                    .addComponent(cb29)
                    .addComponent(cb30))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb31)
                    .addComponent(cb32))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb20ActionPerformed
        m.change(cb20, 20);
    }//GEN-LAST:event_cb20ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        m.change(cb1, 1);
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        m.change(cb3, 3);
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        m.change(cb4, 4);
    }//GEN-LAST:event_cb4ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        m.change(cb5, 5);
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb16ActionPerformed
        m.change(cb16, 16);
    }//GEN-LAST:event_cb16ActionPerformed

    private void cb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb7ActionPerformed
        m.change(cb7, 7);
    }//GEN-LAST:event_cb7ActionPerformed

    private void cb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb8ActionPerformed
        m.change(cb8, 8);
    }//GEN-LAST:event_cb8ActionPerformed

    private void cb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb9ActionPerformed
        m.change(cb9, 9);
    }//GEN-LAST:event_cb9ActionPerformed

    private void cb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb10ActionPerformed
        m.change(cb10, 10);
    }//GEN-LAST:event_cb10ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
        m.change(cb6, 6);
    }//GEN-LAST:event_cb6ActionPerformed

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
        m.change(cb12, 12);
    }//GEN-LAST:event_cb12ActionPerformed

    private void cb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb13ActionPerformed
        m.change(cb13, 13);
    }//GEN-LAST:event_cb13ActionPerformed

    private void cb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb14ActionPerformed
        m.change(cb14, 14);
    }//GEN-LAST:event_cb14ActionPerformed

    private void cb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb15ActionPerformed
        m.change(cb15, 15);
    }//GEN-LAST:event_cb15ActionPerformed

    private void cb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb11ActionPerformed
        m.change(cb11, 11);
    }//GEN-LAST:event_cb11ActionPerformed

    private void cb17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb17ActionPerformed
        m.change(cb17, 17);
    }//GEN-LAST:event_cb17ActionPerformed

    private void cb18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb18ActionPerformed
        m.change(cb18, 18);
    }//GEN-LAST:event_cb18ActionPerformed

    private void cb19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb19ActionPerformed
        m.change(cb19, 19);
    }//GEN-LAST:event_cb19ActionPerformed

    private void cb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb21ActionPerformed
        m.change(cb21, 21);
    }//GEN-LAST:event_cb21ActionPerformed

    private void cb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb22ActionPerformed
        m.change(cb22, 22);
    }//GEN-LAST:event_cb22ActionPerformed

    private void cb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb23ActionPerformed
        m.change(cb23, 23);
    }//GEN-LAST:event_cb23ActionPerformed

    private void cb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb24ActionPerformed
        m.change(cb24, 24);
    }//GEN-LAST:event_cb24ActionPerformed

    private void cb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb25ActionPerformed
        m.change(cb25, 25);
    }//GEN-LAST:event_cb25ActionPerformed

    private void cb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb26ActionPerformed
        m.change(cb26, 26);
    }//GEN-LAST:event_cb26ActionPerformed

    private void cb27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb27ActionPerformed
        m.change(cb27, 27);
    }//GEN-LAST:event_cb27ActionPerformed

    private void cb28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb28ActionPerformed
        m.change(cb28, 28);
    }//GEN-LAST:event_cb28ActionPerformed

    private void cb29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb29ActionPerformed
        m.change(cb29, 29);
    }//GEN-LAST:event_cb29ActionPerformed

    private void cb30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb30ActionPerformed
        m.change(cb30, 30);
    }//GEN-LAST:event_cb30ActionPerformed

    private void cb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb31ActionPerformed
        m.change(cb31, 31);
    }//GEN-LAST:event_cb31ActionPerformed

    private void cb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb32ActionPerformed
        m.change(cb32, 32);
    }//GEN-LAST:event_cb32ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        m.change(cb2, 2);
    }//GEN-LAST:event_cb2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb10;
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb12;
    private javax.swing.JCheckBox cb13;
    private javax.swing.JCheckBox cb14;
    private javax.swing.JCheckBox cb15;
    private javax.swing.JCheckBox cb16;
    private javax.swing.JCheckBox cb17;
    private javax.swing.JCheckBox cb18;
    private javax.swing.JCheckBox cb19;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb20;
    private javax.swing.JCheckBox cb21;
    private javax.swing.JCheckBox cb22;
    private javax.swing.JCheckBox cb23;
    private javax.swing.JCheckBox cb24;
    private javax.swing.JCheckBox cb25;
    private javax.swing.JCheckBox cb26;
    private javax.swing.JCheckBox cb27;
    private javax.swing.JCheckBox cb28;
    private javax.swing.JCheckBox cb29;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb30;
    private javax.swing.JCheckBox cb31;
    private javax.swing.JCheckBox cb32;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox cb7;
    private javax.swing.JCheckBox cb8;
    private javax.swing.JCheckBox cb9;
    // End of variables declaration//GEN-END:variables
}
