import java.awt.Toolkit;
import javax.swing.tree.DefaultMutableTreeNode;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author negi
 */
public class NewJFrame extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x = (int) tk.getScreenSize().getWidth();
        int y = (int) tk.getScreenSize().getHeight()-40;
        this.setSize(x,y);
        }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        k = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        lbl = new javax.swing.JLabel();
        h = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gate Syllabus Tracking");
        setBackground(new java.awt.Color(51, 102, 255));
        setPreferredSize(new java.awt.Dimension(1364, 689));

        k.setBackground(new java.awt.Color(153, 153, 255));

        jTree1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Gate");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("DBMS");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("TOC");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Computer Networks");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Probability");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("OS");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Combinatories");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Data Structure");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Compiler Design");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Calculus");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Set and Algebra");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Algorithm");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Aptitude");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("CO");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Linear Algebra");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("DSD");
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTree1ComponentAdded(evt);
            }
        });
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jTree1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTree1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl.setText("COMPUTER SCIENCE");

        h.setBackground(new java.awt.Color(255, 255, 255));
        h.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        h.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\negi\\Desktop\\Untitled.png")); // NOI18N

        javax.swing.GroupLayout hLayout = new javax.swing.GroupLayout(h);
        h.setLayout(hLayout);
        hLayout.setHorizontalGroup(
            hLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        hLayout.setVerticalGroup(
            hLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        name.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N

        javax.swing.GroupLayout kLayout = new javax.swing.GroupLayout(k);
        k.setLayout(kLayout);
        kLayout.setHorizontalGroup(
            kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kLayout.createSequentialGroup()
                        .addComponent(lbl)
                        .addGap(268, 268, 268)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(h, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kLayout.setVerticalGroup(
            kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(h, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
     
    }//GEN-LAST:event_jTree1ValueChanged

    private void jTree1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTree1KeyPressed
       
    }//GEN-LAST:event_jTree1KeyPressed

    private void jTree1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTree1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1ComponentAdded

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
        String p = selectedNode.getUserObject().toString();

        if (p.equalsIgnoreCase("algorithm")) {
            name.setText("Algorithm");

            h.removeAll();
            h.repaint();
            h.revalidate();

            algo b = new algo();
            h.add(b);

            b.setBounds(5, 5, 860, 411);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("aptitude")) {
            name.setText("Aptitude");

            h.removeAll();
            h.repaint();
            h.revalidate();

            apti k = new apti();
            h.add(k);

            k.setBounds(5, 5, 1010, 574);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("calculus")) {
            name.setText("Calculus");

            h.removeAll();
            h.repaint();
            h.revalidate();

            calculus c = new calculus();
            h.add(c);

            c.setBounds(5, 5, 802, 182);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("computer networks")) {
            name.setText("Computer Networks");

            h.removeAll();
            h.repaint();
            h.revalidate();

            cn n = new cn();
            h.add(n);

            n.setBounds(5, 5, 952, 465);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("co")) {
            name.setText("Computer Organization");

            h.removeAll();
            h.repaint();
            h.revalidate();

            co o = new co();
            h.add(o);

            o.setBounds(5, 5, 643, 329);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("Combinatories")) {
            name.setText("Combinatories");

            h.removeAll();
            h.repaint();
            h.revalidate();

            combin cm = new combin();
            h.add(cm);

            cm.setBounds(5, 5, 701, 109);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("compiler design")) {
            name.setText("Compiler Design");

            h.removeAll();
            h.repaint();
            h.revalidate();

            compiler cd = new compiler();
            h.add(cd);

            cd.setBounds(5, 5, 635, 243);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("dbms")) {
            name.setText("DBMS");

            h.removeAll();
            h.repaint();
            h.revalidate();

            dbms db = new dbms();
            h.add(db);

            db.setBounds(5, 5, 937, 265);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("data structure")) {
            name.setText("Data Structure");

            h.removeAll();
            h.repaint();
            h.revalidate();

            ds s = new ds();
            h.add(s);

            s.setBounds(5, 5, 784, 467);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("dsd")) {
            name.setText("Digital System Design");

            h.removeAll();
            h.repaint();
            h.revalidate();

            dsd sd = new dsd();
            h.add(sd);

            sd.setBounds(5, 5, 744, 176);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("linear algebra")) {
            name.setText("Linear Algebra");

            h.removeAll();
            h.repaint();
            h.revalidate();

            linear l = new linear();
            h.add(l);

            l.setBounds(5, 5, 868, 310);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("os")) {
            name.setText("Operating System");

            h.removeAll();
            h.repaint();
            h.revalidate();

            os s = new os();
            h.add(s);

            s.setBounds(5, 5, 758, 246);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("probability")) {
            name.setText("Probability");

            h.removeAll();
            h.repaint();
            h.revalidate();

            prob pr = new prob();
            h.add(pr);

            pr.setBounds(5, 5, 795, 243);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("set and algebra")) {
            name.setText("Set and Algebra");

            h.removeAll();
            h.repaint();
            h.revalidate();

            set se = new set();
            h.add(se);

            se.setBounds(5, 5, 709, 310);
            h.repaint();
            h.revalidate();

        } else if (p.equalsIgnoreCase("toc")) {
            name.setText("TOC");

            h.removeAll();
            h.repaint();
            h.revalidate();

            toc t = new toc();
            h.add(t);

            t.setBounds(5, 5, 907, 377);
            h.repaint();
            h.revalidate();

        }

    }//GEN-LAST:event_jTree1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel h;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel k;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
